-- MySQL Script generated by MySQL Workbench
-- Fri Nov  7 16:04:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema What_the_dog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `What_the_dog` ;

-- -----------------------------------------------------
-- Schema What_the_dog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `What_the_dog` DEFAULT CHARACTER SET utf8 ;
USE `What_the_dog` ;

-- -----------------------------------------------------
-- Table `What_the_dog`.`Locality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `What_the_dog`.`Locality` ;

CREATE TABLE IF NOT EXISTS `What_the_dog`.`Locality` (
  `idLocality` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `postal_code` INT NULL,
  `toponym` VARCHAR(50) NULL,
  `canton_code` VARCHAR(2) NULL,
  `language_code` VARCHAR(2) NULL,
  PRIMARY KEY (`idLocality`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `What_the_dog`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `What_the_dog`.`Service` ;

CREATE TABLE IF NOT EXISTS `What_the_dog`.`Service` (
  `idService` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `place` VARCHAR(45) NULL,
  `duration_service` DATETIME NULL,
  PRIMARY KEY (`idService`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `What_the_dog`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `What_the_dog`.`Customer` ;

CREATE TABLE IF NOT EXISTS `What_the_dog`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(50) NULL,
  `firstname` VARCHAR(30) NULL,
  `gender` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `tel_number` VARCHAR(45) NULL,
  `postal_address` VARCHAR(45) NULL,
  `Locality_idLocality` INT NOT NULL,
  `Service_idService` INT NOT NULL,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customer_Locality_idx` (`Locality_idLocality` ASC) VISIBLE,
  INDEX `fk_Customer_Service1_idx` (`Service_idService` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Locality`
    FOREIGN KEY (`Locality_idLocality`)
    REFERENCES `What_the_dog`.`Locality` (`idLocality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_Service1`
    FOREIGN KEY (`Service_idService`)
    REFERENCES `What_the_dog`.`Service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `What_the_dog`.`Race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `What_the_dog`.`Race` ;

CREATE TABLE IF NOT EXISTS `What_the_dog`.`Race` (
  `idRace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `morphotype` VARCHAR(45) NULL,
  `classification` VARCHAR(45) NULL,
  `sizeMin_F` INT NULL,
  `sizeMax_F` INT NULL,
  `sizeMin_M` INT NULL,
  `sizeMax_M` INT NULL,
  `weightMin_F` INT NULL,
  `weightMax_F` INT NULL,
  `weightMin_M` INT NULL,
  `weightMax_M` INT NULL,
  `life_expectancy` INT NULL,
  PRIMARY KEY (`idRace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `What_the_dog`.`dog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `What_the_dog`.`dog` ;

CREATE TABLE IF NOT EXISTS `What_the_dog`.`dog` (
  `iddog` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `sex` VARCHAR(20) NULL,
  `crossing` TINYINT NULL,
  `birthdate` DATE NULL,
  `dead` TINYINT NULL,
  `sterilized` TINYINT NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Race_idRace` INT NOT NULL,
  PRIMARY KEY (`iddog`),
  INDEX `fk_dog_Customer1_idx` (`Customer_idCustomer` ASC) VISIBLE,
  INDEX `fk_dog_Race1_idx` (`Race_idRace` ASC) VISIBLE,
  CONSTRAINT `fk_dog_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `What_the_dog`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dog_Race1`
    FOREIGN KEY (`Race_idRace`)
    REFERENCES `What_the_dog`.`Race` (`idRace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `What_the_dog`.`Illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `What_the_dog`.`Illness` ;

CREATE TABLE IF NOT EXISTS `What_the_dog`.`Illness` (
  `idillness` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(70) NULL,
  `symptoms` VARCHAR(50) NULL,
  `means` VARCHAR(45) NULL,
  `remedy` VARCHAR(50) NULL,
  `vaccine` TINYINT NULL,
  `zoonosis` TINYINT NULL,
  PRIMARY KEY (`idillness`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `What_the_dog`.`dog_has_Illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `What_the_dog`.`dog_has_Illness` ;

CREATE TABLE IF NOT EXISTS `What_the_dog`.`dog_has_Illness` (
  `dog_iddog` INT NOT NULL,
  `Illness_idillness` INT NOT NULL,
  PRIMARY KEY (`dog_iddog`, `Illness_idillness`),
  INDEX `fk_dog_has_Illness_Illness1_idx` (`Illness_idillness` ASC) VISIBLE,
  INDEX `fk_dog_has_Illness_dog1_idx` (`dog_iddog` ASC) VISIBLE,
  CONSTRAINT `fk_dog_has_Illness_dog1`
    FOREIGN KEY (`dog_iddog`)
    REFERENCES `What_the_dog`.`dog` (`iddog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dog_has_Illness_Illness1`
    FOREIGN KEY (`Illness_idillness`)
    REFERENCES `What_the_dog`.`Illness` (`idillness`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
